Multiple fixes
PHP-Outburst/myUPB pull request #45
Opened 2017-06-29 22:26 UTC by phpcodex

2017-06-30 08:48 UTC, Halamix2 commented
Fixes #39 and #42

2017-06-30 17:51 UTC, halamix2 requested changes

2017-06-30 17:51 UTC, halamix2 commented on pmblocklist.php
> +} elseif($_POST["action"] == "unblock") {
Every other `if` checks for $_GET, maybe we should change the form to GET instead of changing if to POST?

2017-06-30 18:55 UTC, Halamix2 commented on pmblocklist.php
> +} elseif($_POST["action"] == "unblock") {
We'll stick to POST for now, since it can be longer than GET, and less ugly when unblocking many users

2017-06-30 18:55 UTC, halamix2 approved these changes

2017-06-30 18:55 UTC, merged

2017-07-01 03:36 UTC, blackcrack commented
Hi :)
https://stackoverflow.com/questions/16517097/php-get-or-post-security
https://stackoverflow.com/questions/5287145/php-security-using-post-instead-of-get-to-protect-against-xsrf
http://cowbelljs.blogspot.de/2011/12/get-and-post-security.html

the answers was give by the past ;) 
i read also the oracle Internet, because the Oracle have many more experience .. and at last take i am my feeling.. but before i suck up the information from the internet to get experiences and at last it is my feeling.
So, "post" it is sending something, "get" it is to become something .. and at end it is the security and the feeling..


best regards
blacky

2017-07-21 21:36 UTC, Halamix2 commented
Fixes #13 as well, I've overlooked it